<?php

function arabicno_to_ordinal($number){
    $first="الأول";
    ${1}="الحادي";
    ${2}="الثاني";
    ${3}="الثالث";
    ${4}="الرابع";
    ${5}="الخامس";
    ${6}="السادس";
    ${7}="السابع";
    ${8}="الثامن";
    ${9}="التاسع";
    ${20}="العشرون";
    ${30}="الثلاثون";
    ${40}="الأربعون";
    ${50}="الخمسون";
    ${60}="الستون";
    ${70}="السبعون";
    ${80}="الثمانون";
    ${90}="التسعون";  
    $and="و";
    switch ((int)$number){
            case 1:return "الأول";
            case 2:return "الثاني";
            case 3:return "الثالث";
            case 4:return "الرابع";
            case 5:return "الخامس";
            case 6:return "السادس";
            case 7:return "السابع";
            case 8:return "الثامن";
            case 9:return "التاسع";
            case 10:return "العاشر";
            case 11:return "الحادي عشر";
            case 12:return "الثاني عشر";
            case 13:return "الثالث عشر";
            case 14:return "الرابع عشر";
            case 15:return "الخامس عشر";
            case 16:return "السادس عشر";
            case 17:return "السابع عشر";
            case 18:return "الثامن عشر";
            case 19:return "التاسع عشر";
            case 20:return ${20};
            case 21:return ${1} ." ".$and. ${20};
            case 22:return ${2} ." ".$and. ${20};
            case 23:return ${2} ." ".$and. ${20};
            case 24:return ${2} ." ".$and. ${20};
            case 25:return ${5} ." ".$and. ${20};
            case 26:return ${6} ." ".$and. ${20};
            case 27:return ${7} ." ".$and. ${20};
            case 28:return ${8} ." ".$and. ${20};
            case 29:return ${9} ." ".$and. ${20};          
            case 30:return ${30}; 
            case 31:return ${1} ." ".$and. ${30};
            case 32:return ${2} ." ".$and. ${30};
            case 33:return ${3} ." ".$and. ${30};
            case 34:return ${4} ." ".$and. ${30};
            case 35:return ${5} ." ".$and. ${30};
            case 36:return ${6} ." ".$and. ${30};
            case 37:return ${7} ." ".$and. ${30};
            case 38:return ${8} ." ".$and. ${30};
            case 39:return ${9} ." ".$and. ${30};
            case 40:return ${40};
            case 41:return ${1} ." ".$and. ${40};
            case 42:return ${2} ." ".$and. ${40};
            case 43:return ${3} ." ".$and. ${40};
            case 44:return ${4} ." ".$and. ${40};
            case 45:return ${5} ." ".$and. ${40};
            case 46:return ${6} ." ".$and. ${40};
            case 47:return ${7} ." ".$and. ${40};
            case 48:return ${8} ." ".$and. ${40};
            case 49:return ${9} ." ".$and. ${40};
            case 50:return ${50};
            case 51:return ${1} ." ".$and. ${50};
            case 52:return ${2} ." ".$and. ${50};
            case 53:return ${3} ." ".$and. ${50};
            case 54:return ${4} ." ".$and. ${50};
            case 55:return ${5} ." ".$and. ${50};
            case 56:return ${6} ." ".$and. ${50};
            case 57:return ${7} ." ".$and. ${50};
            case 58:return ${8} ." ".$and. ${50};
            case 59:return ${9} ." ".$and. ${50};
            case 60:return ${60};
            case 61:return ${1} ." ".$and. ${60};
            case 62:return ${2} ." ".$and. ${60};
            case 63:return ${3} ." ".$and. ${60};
            case 64:return ${4} ." ".$and. ${60};
            case 65:return ${5} ." ".$and. ${60};
            case 66:return ${6} ." ".$and. ${60};
            case 67:return ${7} ." ".$and. ${60};
            case 68:return ${8} ." ".$and. ${60};
            case 69:return ${9} ." ".$and. ${60};
            case 70:return ${70};
            case 71:return ${1} ." ".$and. ${70};
            case 72:return ${2} ." ".$and. ${70};
            case 73:return ${3} ." ".$and. ${70};
            case 74:return ${4} ." ".$and. ${70};
            case 75:return ${5} ." ".$and. ${70};
            case 76:return ${6} ." ".$and. ${70};
            case 77:return ${7} ." ".$and. ${70};
            case 78:return ${8} ." ".$and. ${70};
            case 79:return ${9} ." ".$and. ${70};
            case 80:return ${80};
            case 81:return ${1} ." ".$and. ${80};
            case 82:return ${2} ." ".$and. ${80};
            case 83:return ${3} ." ".$and. ${80};
            case 84:return ${4} ." ".$and. ${80};
            case 85:return ${5} ." ".$and. ${80};
            case 86:return ${6}." ".$and. ${80};
            case 87:return ${7} ." ".$and. ${80};
            case 88:return ${8} ." ".$and. ${80};
            case 89:return ${9} ." ".$and. ${80};
            case 90:return ${90};
            case 91:return ${1} ." ".$and. ${90};
            case 92:return ${2} ." ".$and. ${90};
            case 93:return ${3} ." ".$and. ${90};
            case 94:return ${4} ." ".$and. ${90};
            case 95:return ${5} ." ".$and. ${90};
            case 96:return ${6} ." ".$and. ${90};
            case 97:return ${7} ." ".$and. ${90};
            case 98:return ${8} ." ".$and. ${90};
            case 99:return ${9} ." ".$and. ${90};
            case 100:return "المئة";
            default:return $number;

        }
    }
function arabicno_to_ordinal_fem($number){
    $first="الأول";
    ${1}="الحادي";
    ${2}="الثاني";
    ${3}="الثالث";
    ${4}="الرابع";
    ${5}="الخامس";
    ${6}="السادس";
    ${7}="السابع";
    ${8}="الثامن";
    ${9}="التاسع";
    ${20}="العشرون";
    ${30}="الثلاثون";
    ${40}="الأربعون";
    ${50}="الخمسون";
    ${60}="الستون";
    ${70}="السبعون";
    ${80}="الثمانون";
    ${90}="التسعون";  
    $and="و";
    $fem="ة";
    switch ((int)$number){
        case 1:return "الأول".$fem;
        case 2:return "الثانية";
        case 3:return "الثالثة";
        case 4:return "الرابعة";
        case 5:return "الخامسة";
        case 6:return "السادسة";
        case 7:return "السابعة";
        case 8:return "الثامنة";
        case 9:return "التاسعة";
        case 10:return "العاشرة";
        case 11:return ${1}.$fem." "."عشر".$fem;
        case 12:return ${2}.$fem." "."عشر".$fem;
        case 13:return ${3}.$fem." "."عشر".$fem;
        case 14:return ${4}.$fem." "."عشر".$fem;
        case 15:return ${5}.$fem." "."عشر".$fem;
        case 16:return ${6}.$fem." "."عشر".$fem;
        case 17:return ${7}.$fem." "."عشر".$fem;
        case 18:return ${8}.$fem." "."عشر".$fem;
        case 19:return ${9}.$fem." "."عشر".$fem;
        case 20:return ${20};
        case 21:return ${1}.$fem ." ".$and. ${20};
        case 22:return ${2}.$fem ." ".$and. ${20};
        case 23:return ${2}.$fem ." ".$and. ${20};
        case 24:return ${2}.$fem ." ".$and. ${20};
        case 25:return ${5}.$fem ." ".$and. ${20};
        case 26:return ${6}.$fem ." ".$and. ${20};
        case 27:return ${7}.$fem ." ".$and. ${20};
        case 28:return ${8}.$fem ." ".$and. ${20};
        case 29:return ${9}.$fem ." ".$and. ${20};          
        case 30:return ${30}; 
        case 31:return ${1}.$fem ." ".$and. ${30};
        case 32:return ${2}.$fem ." ".$and. ${30};
        case 33:return ${3}.$fem ." ".$and. ${30};
        case 34:return ${4}.$fem ." ".$and. ${30};
        case 35:return ${5}.$fem ." ".$and. ${30};
        case 36:return ${6}.$fem ." ".$and. ${30};
        case 37:return ${7}.$fem ." ".$and. ${30};
        case 38:return ${8}.$fem ." ".$and. ${30};
        case 39:return ${9}.$fem ." ".$and. ${30};
        case 40:return ${40};
        case 41:return ${1}.$fem ." ".$and. ${40};
        case 42:return ${2}.$fem ." ".$and. ${40};
        case 43:return ${3}.$fem ." ".$and. ${40};
        case 44:return ${4}.$fem ." ".$and. ${40};
        case 45:return ${5}.$fem ." ".$and. ${40};
        case 46:return ${6}.$fem ." ".$and. ${40};
        case 47:return ${7}.$fem ." ".$and. ${40};
        case 48:return ${8}.$fem ." ".$and. ${40};
        case 49:return ${9}.$fem ." ".$and. ${40};
        case 50:return ${50};
        case 51:return ${1}.$fem ." ".$and. ${50};
        case 52:return ${2}.$fem ." ".$and. ${50};
        case 53:return ${3}.$fem ." ".$and. ${50};
        case 54:return ${4}.$fem ." ".$and. ${50};
        case 55:return ${5}.$fem ." ".$and. ${50};
        case 56:return ${6}.$fem ." ".$and. ${50};
        case 57:return ${7}.$fem ." ".$and. ${50};
        case 58:return ${8}.$fem ." ".$and. ${50};
        case 59:return ${9}.$fem ." ".$and. ${50};
        case 60:return ${60};
        case 61:return ${1}.$fem ." ".$and. ${60};
        case 62:return ${2}.$fem ." ".$and. ${60};
        case 63:return ${3}.$fem ." ".$and. ${60};
        case 64:return ${4}.$fem ." ".$and. ${60};
        case 65:return ${5}.$fem ." ".$and. ${60};
        case 66:return ${6}.$fem ." ".$and. ${60};
        case 67:return ${7}.$fem ." ".$and. ${60};
        case 68:return ${8}.$fem ." ".$and. ${60};
        case 69:return ${9}.$fem ." ".$and. ${60};
        case 70:return ${70};
        case 71:return ${1}.$fem ." ".$and. ${70};
        case 72:return ${2}.$fem ." ".$and. ${70};
        case 73:return ${3}.$fem ." ".$and. ${70};
        case 74:return ${4}.$fem ." ".$and. ${70};
        case 75:return ${5}.$fem." ".$and. ${70};
        case 76:return ${6}.$fem ." ".$and. ${70};
        case 77:return ${7}.$fem ." ".$and. ${70};
        case 78:return ${8}.$fem ." ".$and. ${70};
        case 79:return ${9}.$fem ." ".$and. ${70};
        case 80:return ${80};
        case 81:return ${1}.$fem ." ".$and. ${80};
        case 82:return ${2}.$fem ." ".$and. ${80};
        case 83:return ${3}.$fem ." ".$and. ${80};
        case 84:return ${4}.$fem ." ".$and. ${80};
        case 85:return ${5}.$fem ." ".$and. ${80};
        case 86:return ${6}.$fem ." ".$and. ${80};
        case 87:return ${7}.$fem ." ".$and. ${80};
        case 88:return ${8}.$fem ." ".$and. ${80};
        case 89:return ${9}.$fem ." ".$and. ${80};
        case 90:return ${90};
        case 91:return ${1}.$fem ." ".$and. ${90};
        case 92:return ${2}.$fem ." ".$and. ${90};
        case 93:return ${3}.$fem ." ".$and. ${90};
        case 94:return ${4}.$fem ." ".$and. ${90};
        case 95:return ${5}.$fem ." ".$and. ${90};
        case 96:return ${6}.$fem ." ".$and. ${90};
        case 97:return ${7}.$fem ." ".$and. ${90};
        case 98:return ${8}.$fem ." ".$and. ${90};
        case 99:return ${9}.$fem ." ".$and. ${90};
        case 100:return "المئة";
        default:return $number;

    }
}
        ?>
